name: Generate Snake

on:
  schedule:
  
  
    - cron: "0 */1 * * *"
# "*/1 * * * *"
# cron(0/5
# "0 */1 * * *"


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v2
        id: bylickilabs-Snake
        with:
          github_user_name: miguel220
          outputs: |
                    dist/github-contribution-grid-snake2.svg?palette=github-dark&color_snake=cornflowerblue
      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
